language: node_js
sudo: required
before_script:
  - npm install -g bower polylint web-component-tester
  - bower install
  #- polylint
node_js: stable
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run wct
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then wct -s 'default'; fi"
  - bash ./.gp.sh uhawaii-system-its-mis-components google-at-uh Travis_CI no_reply@hawaii.edu
dist: trusty